"""
Graph domain models for CatRAG Knowledge Graph.

This module defines domain models for graph entities aligned with
the CatRAG category-labeled schema.
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from datetime import datetime
from enum import Enum


class NodeCategory(str, Enum):
    """
    CatRAG Node Categories - STANDARDIZED SCHEMA
    
    All values are UPPER_SNAKE_CASE to match Neo4j labels directly.
    This fixes the previous MonHoc vs MON_HOC inconsistency.
    """
    MON_HOC = "MON_HOC"  # Changed from "MonHoc"
    QUY_DINH = "QUY_DINH"  # Changed from "QuyDinh"
    DIEU_KIEN = "DIEU_KIEN"  # Changed from "DieuKien"
    KHOA = "KHOA"  # Changed from "Khoa"
    NGANH = "NGANH"  # Changed from "Nganh"
    CHUONG_TRINH_DAO_TAO = "CHUONG_TRINH_DAO_TAO"  # Changed from "ChuongTrinhDaoTao"
    SINH_VIEN = "SINH_VIEN"  # Changed from "SinhVien"
    KY_HOC = "KY_HOC"  # Changed from "KyHoc"
    GIANG_VIEN = "GIANG_VIEN"  # Changed from "GiangVien"
    HOC_PHI = "HOC_PHI"  # Changed from "HocPhi"


class RelationshipType(str, Enum):
    """CatRAG Relationship Types"""
    # Hierarchical
    THUOC_KHOA = "THUOC_KHOA"  # MON_HOC/NGANH → KHOA
    CUA_NGANH = "CUA_NGANH"  # MON_HOC → NGANH
    THUOC_CHUONG_TRINH = "THUOC_CHUONG_TRINH"  # MON_HOC → CHUONG_TRINH_DAO_TAO
    QUAN_LY = "QUAN_LY"  # KHOA → NGANH/MON_HOC (management relationship)
    
    # Prerequisites (CRITICAL for routing)
    DIEU_KIEN_TIEN_QUYET = "DIEU_KIEN_TIEN_QUYET"  # MON_HOC → MON_HOC only
    YEU_CAU_DIEU_KIEN = "YEU_CAU_DIEU_KIEN"  # MON_HOC → DIEU_KIEN
    QUY_DINH_DIEU_KIEN = "QUY_DINH_DIEU_KIEN"  # QUY_DINH → DIEU_KIEN
    
    # Applicability
    AP_DUNG_CHO = "AP_DUNG_CHO"  # QUY_DINH → (SINH_VIEN/NGANH/KHOA)
    
    # Semantic
    LIEN_QUAN_NOI_DUNG = "LIEN_QUAN_NOI_DUNG"  # MON_HOC → MON_HOC
    THAY_THE = "THAY_THE"  # MON_HOC → MON_HOC
    BO_SUNG = "BO_SUNG"  # MON_HOC → MON_HOC
    
    # Scheduling
    HOC_TRONG = "HOC_TRONG"  # MON_HOC → KY_HOC
    DAY = "DAY"  # GIANG_VIEN → MON_HOC


@dataclass
class GraphNode:
    """
    Domain model for a graph node.
    
    Attributes:
        id: Unique identifier (optional, generated by Neo4j)
        category: Node category from CatRAG schema
        properties: Node properties as dict
    """
    category: NodeCategory
    properties: Dict[str, Any]
    id: Optional[str] = None
    
    def __post_init__(self):
        """Validate node properties against category requirements"""
        self._validate_properties()
    
    def _validate_properties(self):
        """Validate that required properties are present"""
        required_props = self._get_required_properties()
        for prop in required_props:
            if prop not in self.properties:
                raise ValueError(f"Missing required property '{prop}' for category {self.category}")
    
    def _get_required_properties(self) -> List[str]:
        """Get required properties for this node category"""
        requirements = {
            NodeCategory.MON_HOC: ["code", "name", "credits"],
            NodeCategory.QUY_DINH: ["id", "title", "year"],
            NodeCategory.DIEU_KIEN: ["id", "type", "description"],
            NodeCategory.KHOA: ["code", "name"],
            NodeCategory.NGANH: ["code", "name"],
            NodeCategory.CHUONG_TRINH_DAO_TAO: ["id", "name", "year"],
            NodeCategory.SINH_VIEN: ["cohort"],
            NodeCategory.KY_HOC: ["code", "year"],
        }
        return requirements.get(self.category, [])


@dataclass
class GraphRelationship:
    """
    Domain model for a graph relationship.
    
    Attributes:
        source_id: ID of source node
        target_id: ID of target node
        rel_type: Relationship type from CatRAG schema
        properties: Relationship properties
    """
    source_id: str
    target_id: str
    rel_type: RelationshipType
    properties: Dict[str, Any] = field(default_factory=dict)


@dataclass
class GraphPath:
    """
    Domain model for a path in the graph.
    
    Represents a sequence of nodes connected by relationships.
    Useful for prerequisite chains, organizational hierarchies, etc.
    """
    nodes: List[GraphNode]
    relationships: List[GraphRelationship]
    length: int = field(init=False)
    
    def __post_init__(self):
        self.length = len(self.relationships)
    
    def get_node_ids(self) -> List[str]:
        """Get list of node IDs in the path"""
        return [node.id for node in self.nodes if node.id]
    
    def get_relationship_types(self) -> List[str]:
        """Get list of relationship types in the path"""
        return [rel.rel_type.value for rel in self.relationships]


@dataclass
class SubGraph:
    """
    Domain model for a subgraph.
    
    Represents a subset of the knowledge graph, useful for
    context retrieval and visualization.
    """
    nodes: List[GraphNode]
    relationships: List[GraphRelationship]
    center_node_id: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def get_node_count(self) -> int:
        """Get number of nodes in subgraph"""
        return len(self.nodes)
    
    def get_relationship_count(self) -> int:
        """Get number of relationships in subgraph"""
        return len(self.relationships)
    
    def get_categories(self) -> List[str]:
        """Get unique node categories in subgraph"""
        return list(set(node.category.value for node in self.nodes))


@dataclass
class GraphQuery:
    """
    Domain model for graph queries.
    
    Encapsulates query parameters for graph operations.
    """
    query_type: str  # e.g., "traverse", "shortest_path", "subgraph"
    start_node_id: Optional[str] = None
    end_node_id: Optional[str] = None
    relationship_types: List[RelationshipType] = field(default_factory=list)
    max_depth: int = 2
    filters: Dict[str, Any] = field(default_factory=dict)
    limit: int = 10


@dataclass
class QueryIntent(str, Enum):
    """
    CatRAG Query Intent Categories for Router Agent.
    
    Each intent maps to a specific retrieval strategy.
    """
    TIEN_QUYET = "tien_quyet"  # Prerequisites → Graph traversal
    MO_TA_MON_HOC = "mo_ta_mon_hoc"  # Course description → Vector search
    DIEU_KIEN_TOT_NGHIEP = "dieu_kien_tot_nghiep"  # Graduation requirements → Multi-hop graph
    CHUONG_TRINH_DAO_TAO = "chuong_trinh_dao_tao"  # Curriculum → Graph traversal
    QUY_DINH_HOC_VU = "quy_dinh_hoc_vu"  # Regulations → Hybrid search
    HOC_PHI = "hoc_phi"  # Tuition → Hybrid search
    GENERAL = "general"  # General questions → Hybrid search


@dataclass
class RoutingDecision:
    """
    Routing decision made by Router Agent.
    
    Determines which retrieval strategy to use based on query intent.
    """
    intent: QueryIntent
    confidence: float
    route_to: str  # "graph_traversal", "vector_search", "hybrid_search", "multi_hop_graph"
    extracted_entities: List[Dict[str, Any]] = field(default_factory=list)
    reasoning: Optional[str] = None
    
    def should_use_graph(self) -> bool:
        """Determine if graph retrieval should be used"""
        return self.route_to in ["graph_traversal", "multi_hop_graph", "hybrid_search"]
    
    def should_use_vector(self) -> bool:
        """Determine if vector search should be used"""
        return self.route_to in ["vector_search", "hybrid_search"]


@dataclass
class Entity:
    """
    Extracted entity from text (aligned with CatRAG categories).
    
    Attributes:
        text: Entity text as appears in document
        type: Entity type (matches NodeCategory)
        start: Character start position
        end: Character end position
        confidence: Extraction confidence score
        normalized: Normalized form (e.g., "CNTT" → "Công nghệ thông tin")
    """
    text: str
    type: str  # Should match NodeCategory values
    start: int
    end: int
    confidence: float = 1.0
    normalized: Optional[str] = None
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "text": self.text,
            "type": self.type,
            "start": self.start,
            "end": self.end,
            "confidence": self.confidence,
            "normalized": self.normalized,
            "metadata": self.metadata
        }


@dataclass
class Relation:
    """
    Extracted relation from text.
    
    Attributes:
        source: Source entity
        target: Target entity
        rel_type: Relation type (matches RelationshipType)
        confidence: Extraction confidence
    """
    source: Entity
    target: Entity
    rel_type: str  # Should match RelationshipType values
    confidence: float = 1.0
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary"""
        return {
            "source": self.source.to_dict(),
            "target": self.target.to_dict(),
            "rel_type": self.rel_type,
            "confidence": self.confidence,
            "metadata": self.metadata
        }


# Helper functions for creating common node types

def create_mon_hoc_node(code: str, name: str, credits: int, **kwargs) -> GraphNode:
    """Create a MonHoc (course) node"""
    properties = {
        "code": code,
        "name": name,
        "credits": credits,
        **kwargs
    }
    return GraphNode(category=NodeCategory.MON_HOC, properties=properties)


def create_quy_dinh_node(qd_id: str, title: str, year: int, **kwargs) -> GraphNode:
    """Create a QuyDinh (regulation) node"""
    properties = {
        "id": qd_id,
        "title": title,
        "year": year,
        **kwargs
    }
    return GraphNode(category=NodeCategory.QUY_DINH, properties=properties)


def create_prerequisite_relationship(
    source_course_id: str,
    target_course_id: str,
    required: bool = True
) -> GraphRelationship:
    """Create a prerequisite relationship between courses"""
    return GraphRelationship(
        source_id=target_course_id,  # Note: reversed for prerequisite
        target_id=source_course_id,
        rel_type=RelationshipType.DIEU_KIEN_TIEN_QUYET,
        properties={
            "type": "bat_buoc" if required else "khuyen_nghi",
            "can_study_parallel": False
        }
    )
